### GET method to recover all car records
GET http://localhost:3001/cars

### GET method to recover brand car records
GET http://localhost:3001/cars?brand=honda

### GET method to recover id car records
GET http://localhost:3001/cars/f9e8d7c6-b5a4-3210-9876-abcdef123456

### POST method NEW CAR 
POST http://localhost:3001/cars

### PATCh BY ID
PATCH  http://localhost:3001/cars/{id}

